name: chart_sparkline
description: Beautiful sparkline charts for Flutter.Average line, highest and lowest value.
version: 1.0.12
homepage: https://github.com/biner88/chart_sparkline
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.10.0"
